import fs from "node:fs";

const report = fs.readFileSync("report.md", "utf8");

const esc = s => s.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const inline = s => esc(s).replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/`(.+?)`/g,"<code>$1</code>").replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2">$1</a>');
function md(text) {
  const lines=text.split("\n"); let out="", list=false, quote=false;
  for (const raw of lines) {
    const l=raw.trimEnd();
    if (!l.trim()) { if(list){out+="</ul>";list=false} if(quote){out+="</blockquote>";quote=false} continue; }
    const h=l.match(/^(#{1,4})\s+(.+)/);
    if(h){if(list){out+="</ul>";list=false} out+=`<h${h[1].length} id="${h[2].toLowerCase().replace(/[^a-z0-9]+/g,"-")}">${inline(h[2])}</h${h[1].length}>`;continue}
    if(l.startsWith("> ")){if(!quote){out+="<blockquote>";quote=true} out+=`<p>${inline(l.slice(2))}</p>`;continue}
    if(/^[-*]\s/.test(l)){if(!list){out+="<ul>";list=true} out+=`<li>${inline(l.replace(/^[-*]\s/,""))}</li>`;continue}
    if(/^\d+\.\s/.test(l)){if(!list){out+="<ul>";list=true} out+=`<li>${inline(l.replace(/^\d+\.\s/,""))}</li>`;continue}
    out+=`<p>${inline(l)}</p>`;
  }
  if(list)out+="</ul>"; if(quote)out+="</blockquote>"; return out;
}
const slides = [
["Field note 01","The tested-it position","Run the thing before you explain what it means.","LinkedIn decision system · 28 July 2026"],
["The positioning verdict","Proof beats technical depth","Builder credibility on LinkedIn comes from evidence of building inside accessible posts.","A measured number. A thing that broke. A cost figure. A before-and-after."],
["The quality bar","Every post earns its place","First-hand evidence is the default. A defensible, experience-backed opinion is the exception.","If removing your name changes nothing, do not publish it."],
["Cadence","Two is the floor. Three is a good week.","Daily AI-assisted posting would create takes faster than you can create evidence.","Put daily presence into substantive comments instead."],
["The mix","Four pillars, one clear centre","45% I built, ran, or tested it|30% Plain-English mental models|15% Judgment|10% Trust lens"],
["Pillar A","I built, ran, or tested it","Ship work, test launches, and use tools in real workflows. Show what changed, what failed, and what it means.","This is the flagship because nobody else has your setup."],
["Pillars B–D","Teaching, judgment, trust","Mental models become durable teaching assets. Judgment posts make people follow you. Trust & Safety stays a lens, never the whole identity."],
["Classify the value","Artifacts are not pillars","How it works → B|I built it; here is what happened → A|The system I believe is best → C|Trust topic → D","A guide, skill, workflow, article, video, or carousel is the container. Assign one primary pillar."],
["Two layers, one system","Strategy always. Playbook when routing.","Every LinkedIn task uses the canonical strategy. Add this playbook when deciding whether, when, where, or how an input becomes a post.","For a straightforward draft with idea, platform, and format already chosen, strategy plus the post-builder is enough."],
["The one-minute router","Five gates before a draft","0 Evidence|1 Platform|2 Differentiation|3 Pillar + format|4 Hook"],
["Gate zero","Can you get evidence in under an hour?","Yes: run the test, then write. No: leave a sharp comment or skip it.","That hour is the highest-value hour in the content system."],
["Launch playbook","Concede 0–24h. Own 24–72h.","0–2h: comment on the launch|2–24h: test a real workflow|24–72h: publish one differentiated finding"],
["Choose one lens","One post, one spine","Swap test|Cost and economics|Trust|What they did not say|Decision framework"],
["Seven usable launch angles","Hooks need real results","The swap test · 20-minute migration · Cost translation · Trust lens · Missing detail · Evergreen framework · Anti-hype calibration","Keep every [NEED] placeholder until the evidence exists."],
["Failure modes","What weakens the signal","Assisted-daily volume|News racing|Technical drift|T&S as a crutch|Half-built confession loops|Engagement-bait questions"],
["Weekly rhythm","A small system that survives real life","Daily: 3–5 substantive comments|Twice weekly: pick, test, draft, publish|Launch weeks: one launch post maximum|Monthly: count respected follows and replies"],
["The whole card","Evidence first. Accessible always.","Post 2–3 times a week. Comment daily. Use one lens. Let the hook stand alone. Measure credibility by the people you would want to build with."],
];
const slideHtml=slides.map((s,i)=>{
 const parts=s[2]?.includes("|")?`<ol class="ledger">${s[2].split("|").map(x=>`<li>${x}</li>`).join("")}</ol>`:`<p class="lead">${s[2]||""}</p>`;
 return `<section class="slide" id="slide-${i+1}" aria-labelledby="title-${i+1}"><div class="folio">${String(i+1).padStart(2,"0")}</div><div class="slide-content"><p class="kicker reveal">${s[0]}</p><h2 id="title-${i+1}" class="reveal">${s[1]}</h2><div class="reveal">${parts}</div>${s[3]?`<p class="note reveal">${s[3]}</p>`:""}</div></section>`;
}).join("");
const toc = [...report.matchAll(/^##\s+(.+)$/gm)].map(m=>`<li><a href="#${m[1].toLowerCase().replace(/[^a-z0-9]+/g,"-")}">${inline(m[1])}</a></li>`).join("");
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>LinkedIn Posting Decision System</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Newsreader:opsz,wght@6..72,500;6..72,700&display=swap" rel="stylesheet"><style>
*{box-sizing:border-box}html,body{height:100%;overflow-x:hidden}html{scroll-snap-type:y mandatory;scroll-behavior:smooth}:root{--paper:#f3eedf;--ink:#28251f;--muted:#6d6558;--accent:#ad4f28;--line:#c9bea8;--panel:#ebe3d1;--title-size:clamp(2.2rem,7vw,6.4rem);--h2-size:clamp(1.8rem,5vw,4.8rem);--h3-size:clamp(1rem,2.5vw,1.75rem);--body-size:clamp(.92rem,1.8vw,1.35rem);--small-size:clamp(.68rem,1vw,.84rem);--slide-padding:clamp(1.1rem,5vw,5rem);--content-gap:clamp(.6rem,2vw,2rem);--element-gap:clamp(.3rem,1vw,1rem)}
@media(prefers-color-scheme:dark){:root{--paper:#20201d;--ink:#f1eadc;--muted:#b8ad9b;--accent:#df8259;--line:#4d493f;--panel:#292823}}html[data-theme=light]{--paper:#f3eedf;--ink:#28251f;--muted:#6d6558;--accent:#ad4f28;--line:#c9bea8;--panel:#ebe3d1}html[data-theme=dark]{--paper:#20201d;--ink:#f1eadc;--muted:#b8ad9b;--accent:#df8259;--line:#4d493f;--panel:#292823}
body{margin:0;background:var(--paper);color:var(--ink);font-family:Newsreader,Georgia,serif}.slide{width:100vw;height:100vh;height:100dvh;overflow:hidden;scroll-snap-align:start;display:flex;flex-direction:column;position:relative;border-bottom:1px solid var(--line)}.slide-content{flex:1;display:flex;flex-direction:column;justify-content:center;max-height:100%;overflow:hidden;padding:var(--slide-padding);padding-right:clamp(3.5rem,8vw,8rem);gap:var(--content-gap);max-width:min(92vw,1200px)}.card,.container,.content-box{max-width:min(90vw,1000px);max-height:min(80vh,700px)}.feature-list,.bullet-list{gap:clamp(.4rem,1vh,1rem)}.feature-list li,.bullet-list li{font-size:var(--body-size);line-height:1.4}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,250px),1fr));gap:clamp(.5rem,1.5vw,1rem)}img,.image-container{max-width:100%;max-height:min(50vh,400px);object-fit:contain}
h2{font-size:var(--h2-size);line-height:.92;letter-spacing:-.035em;margin:0;max-width:17ch}.lead{font-size:clamp(1.1rem,2.5vw,2rem);line-height:1.25;max-width:44ch;margin:0}.kicker,.note,.folio,.controls,.ledger{font-family:"DM Mono",monospace}.kicker{color:var(--accent);font-size:var(--small-size);text-transform:uppercase;letter-spacing:.12em;margin:0}.note{font-size:var(--small-size);color:var(--muted);max-width:72ch;border-left:3px solid var(--accent);padding-left:1em}.folio{position:absolute;right:var(--slide-padding);top:var(--slide-padding);color:var(--accent);font-size:clamp(1.8rem,4vw,4rem)}.ledger{list-style:none;padding:0;margin:0;border-top:1px solid var(--line);width:min(100%,780px);font-size:var(--body-size)}.ledger li{padding:clamp(.45rem,1vh,.9rem) 0;border-bottom:1px solid var(--line)}.ledger li::before{content:"→";color:var(--accent);margin-right:1em}.controls{position:fixed;z-index:30;right:clamp(.5rem,1.5vw,1.5rem);bottom:clamp(.5rem,1.5vw,1.5rem);display:flex;gap:.35rem}.controls button,.controls a{min-width:44px;min-height:44px;border:1px solid var(--line);background:var(--paper);color:var(--ink);display:grid;place-items:center;text-decoration:none;font:500 .72rem "DM Mono";padding:.5rem;cursor:pointer}.controls button:focus-visible,.controls a:focus-visible,a:focus-visible{outline:3px solid var(--accent);outline-offset:3px}.progress{position:fixed;z-index:31;top:0;left:0;height:4px;background:var(--accent);width:0}.count{min-width:70px}.reveal{opacity:.01;transform:translateY(12px);transition:.45s ease}.visible .reveal{opacity:1;transform:none}.report{background:var(--panel);padding:clamp(2rem,6vw,6rem) clamp(1rem,5vw,5rem);scroll-snap-align:start}.report-inner{max-width:72ch;margin:auto;font-size:clamp(1rem,1.5vw,1.18rem);line-height:1.65}.report h1{font-size:clamp(2.3rem,7vw,5rem);line-height:1}.report h2{font-size:clamp(1.7rem,4vw,3rem);line-height:1.05;margin-top:2em}.report h3{font-size:clamp(1.25rem,2vw,1.7rem);margin-top:1.7em}.report a{color:var(--accent)}.report li{margin:.45em 0}.toc{border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:1rem 0}.toc li{margin:.2em 0}.appendix-label{font:500 .75rem "DM Mono";color:var(--accent);text-transform:uppercase;letter-spacing:.12em}
@media(max-height:700px){:root{--slide-padding:clamp(.75rem,3vw,2rem);--content-gap:clamp(.4rem,1.5vw,1rem);--title-size:clamp(1.25rem,4.5vw,2.5rem);--h2-size:clamp(1rem,3vw,1.75rem)}}@media(max-height:600px){:root{--slide-padding:clamp(.5rem,2.5vw,1.5rem);--content-gap:clamp(.3rem,1vw,.75rem);--title-size:clamp(1.1rem,4vw,2rem);--body-size:clamp(.7rem,1.2vw,.95rem)}}@media(max-height:500px){:root{--slide-padding:clamp(.4rem,2vw,1rem);--title-size:clamp(1rem,3.5vw,1.5rem);--h2-size:clamp(.9rem,2.5vw,1.25rem);--body-size:clamp(.65rem,1vw,.85rem)}}@media(max-width:600px){:root{--title-size:clamp(1.25rem,7vw,2.5rem)}.grid{grid-template-columns:1fr}.slide-content{padding-right:3.8rem}.folio{font-size:1.2rem}.controls .wide{display:none}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.01ms!important;transition-duration:.2s!important}html{scroll-behavior:auto}.reveal{opacity:1;transform:none}}
@media print{.controls,.progress{display:none}.slide{break-after:page;height:auto;min-height:95vh}.reveal{opacity:1;transform:none}.report{break-before:page}}
</style></head><body><div class="progress" aria-hidden="true"></div><main id="deck">${slideHtml}</main><section class="report" id="report"><div class="report-inner"><p class="appendix-label">Complete source report</p><h2>Reading appendix</h2><nav aria-label="Report contents"><ol class="toc">${toc}</ol></nav>${md(report)}</div></section><nav class="controls" aria-label="Presentation controls"><button id="prev" aria-label="Previous slide">←</button><span class="count" aria-live="polite">1 / ${slides.length}</span><button id="next" aria-label="Next slide">→</button><a class="wide" href="#report">Report</a><button id="theme" aria-label="Toggle theme">◐</button></nav><script>
class Deck{constructor(){this.s=[...document.querySelectorAll(".slide")];this.i=0;this.obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");this.i=this.s.indexOf(e.target);this.paint()}}),{threshold:.55});this.s.forEach(x=>this.obs.observe(x));addEventListener("keydown",e=>{if(["ArrowRight","ArrowDown","PageDown"," "].includes(e.key)){e.preventDefault();this.go(this.i+1)}if(["ArrowLeft","ArrowUp","PageUp"].includes(e.key)){e.preventDefault();this.go(this.i-1)}if(e.key==="Home")this.go(0);if(e.key==="End")this.go(this.s.length-1)});let y=0;document.querySelector("#deck").addEventListener("touchstart",e=>y=e.changedTouches[0].clientY,{passive:true});document.querySelector("#deck").addEventListener("touchend",e=>{let d=y-e.changedTouches[0].clientY;if(Math.abs(d)>50)this.go(this.i+(d>0?1:-1))},{passive:true});prev.onclick=()=>this.go(this.i-1);next.onclick=()=>this.go(this.i+1);this.hash();addEventListener("hashchange",()=>this.hash());this.s[0].classList.add("visible")}go(n){n=Math.max(0,Math.min(this.s.length-1,n));location.hash="slide-"+(n+1);this.s[n].scrollIntoView()}hash(){let m=location.hash.match(/slide-(\\d+)/);if(m)this.go(+m[1]-1)}paint(){document.querySelector(".count").textContent=(this.i+1)+" / "+this.s.length;document.querySelector(".progress").style.width=((this.i+1)/this.s.length*100)+"%"}}new Deck();
const root=document.documentElement,saved=localStorage.getItem("theme");if(saved)root.dataset.theme=saved;theme.onclick=()=>{let now=root.dataset.theme||(matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light");let next=now==="dark"?"light":"dark";root.dataset.theme=next;localStorage.setItem("theme",next)}
</script><noscript><style>.reveal{opacity:1;transform:none}.controls,.progress{display:none}</style></noscript></body></html>`;
fs.writeFileSync("index.html",html);
